
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibhglktotlqvfdnotxxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliaGdsa3RvdGxxdmZkbm90eHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTk2ODgsImV4cCI6MjA2MTU5NTY4OH0.bfeOsTuShbqrYhuXLe4t_BUj7IPU8S8s44Z9AkJlatw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
  }
});
